files:
  - source: /i18n/en-US/*.json
    translation: /i18n/%locale%/%original_file_name%
  - source: /i18n/en-US/admin/*.json
    translation: /i18n/%locale%/admin/%original_file_name%
  - source: /i18n/en-US/config/*.json
    translation: /i18n/%locale%/config/%original_file_name%
  - source: /i18n/en-US/core/*.json
    translation: /i18n/%locale%/core/%original_file_name%
  - source: /i18n/en-US/staff/*.json
    translation: /i18n/%locale%/staff/%original_file_name%
